### PR TITLE
Fix issue #36.

### PR DESCRIPTION
**Pull request by akoptelov**
* Adopt JGit 4.3.1
* Implement ability to specify git options in properties file

### CODE REVIEW

**Comment by akoptelov** [comment]
With this patch it is possible to write
`git.config.core.dirNoGitLinks=true`
to set `dirNoGitLinks` option from `core` section to true.
As a result, JGit will treat a folder containing `.git` directory as plain subfolder, not a separate repository.

**Comment by reinhapa** [comment]
@akoptelov can you tell me what version of the RTC client you use? As I remember, did the old verisons not support the requirements of JGit 4.3. A may have to create a separate branch for the newer RTC versions that support JGit 4.3

**Comment by akoptelov** [comment]
@reinhapa It's 6.0 SDK. What was that unsupported requirements? I didn't change anything that RTC could possibly depend on. I thought it might be Java version (mine was java8), but it also works perfectly with IBM Java 1.6.

**Comment by reinhapa** [comment]
@akoptelov when we migrated, we still had RCT 5.0.1 and some of the users that used this projects had/have 4.0.3

**Comment by akoptelov** [comment]
@reinhapa I can try to do some basic testing against 5.0.2. 4.0.x reaches its end of support very soon. Do we need that?

**Comment by reinhapa** [comment]
@akoptelov I think set after we merged in your other PR #34 after some prior formatting clean ups will do it.

**Comment by akoptelov** [comment]
@reinhapa Just rebuilt and migrated using scmtools 5.0.2. Works fine. Would that be enough?

**Pull request merged**
